### ISSUE TITLE
update (packer) icons to use https

### ISSUE THREAD

**Issue by cfoellmann** [StefanScherer/chocolatey-packages#2]
The packer logo has been moved! You should add the icon from https://packer.io/assets/images/logo_nav-e332793d.png to your repo and use https://rawgit.com/ to generate a cdn link.
This way the logos will be fixed with the next versions.

**Comment by StefanScherer** [comment]
@cfoellmann Thanks! I'll update it soon. Planning to add an uninstall script anyway.

**Comment by StefanScherer** [comment]
Fixed with https://github.com/StefanScherer/chocolatey-packages/commit/12815c3ba8f267139a874cd76e4a4861997e477c
I have uploaded a new package and waits for approval - https://chocolatey.org/packages/packer/0.7.5.20150603
This also contains a new installation location for packer. Feedback is welcome ;-)
